CREATE TABLE ACCOUNTS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT NOT NULL,
  DESCRIPTION TEXT,
  BALANCE INTEGER NOT NULL,
  OPENED_AT INTEGER DEFAULT (strftime('%s', 'now')),
  CLOSED_AT INTEGER
);

CREATE TABLE TRANSACTIONS (
  FROM_ID INTEGER NOT NULL,
  TO_ID INTEGER NOT NULL,
  AMOUNT INTEGER NOT NULL,
  DESCRIPTION TEXT,
  TIMESTAMP INTEGER DEFAULT (strftime('%s', 'now')),
  FOREIGN KEY(FROM_ID) REFERENCES ACCOUNTS(ID),
  FOREIGN KEY(TO_ID) REFERENCES ACCOUNTS(ID)
);

CREATE TRIGGER update_accounts AFTER INSERT ON TRANSACTIONS
BEGIN
  UPDATE ACCOUNTS SET BALANCE=BALANCE-new.AMOUNT WHERE ID=new.FROM_ID;
  UPDATE ACCOUNTS SET BALANCE=BALANCE+new.AMOUNT WHERE ID=new.TO_ID;
END;

INSERT INTO ACCOUNTS(NAME, DESCRIPTION, BALANCE, OPENED_AT)
VALUES (
  "other",
  "Used as a dummy to match against all transactions without a matching account",
  0,
  0
);
