[package]
name = "search"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "search"
path = "main.rs"

[dependencies]
clap = { version = "4.4.0", features = ["derive"] }
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
infer = "0.15.0"
num_cpus = "1.16.0"
regex = "1.10.3"
